import { User, Project, Task, Activity, TeamMember } from './types';

export const mockUsers: User[] = [
  { id: '1', name: 'Admin User', email: 'admin@example.com', role: 'Admin', avatar: '' },
  { id: '2', name: 'Sarah Johnson', email: 'sarah@example.com', role: 'Project Manager', avatar: '' },
  { id: '3', name: 'Mike Chen', email: 'mike@example.com', role: 'Team Member', avatar: '' },
  { id: '4', name: 'Emily Davis', email: 'emily@example.com', role: 'Team Member', avatar: '' },
  { id: '5', name: 'James Wilson', email: 'james@example.com', role: 'Team Member', avatar: '' },
];

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Website Redesign',
    description: 'Complete overhaul of the company website with modern UI/UX',
    status: 'Active',
    deadline: '2026-07-15',
    progress: 65,
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-06-05T14:30:00Z',
  },
  {
    id: '2',
    name: 'Mobile App Development',
    description: 'Build native mobile apps for iOS and Android platforms',
    status: 'Active',
    deadline: '2026-08-20',
    progress: 40,
    createdAt: '2026-05-10T09:00:00Z',
    updatedAt: '2026-06-04T11:20:00Z',
  },
  {
    id: '3',
    name: 'API Integration',
    description: 'Integrate third-party APIs for enhanced functionality',
    status: 'Completed',
    deadline: '2026-05-30',
    progress: 100,
    createdAt: '2026-04-15T08:00:00Z',
    updatedAt: '2026-05-30T16:45:00Z',
  },
  {
    id: '4',
    name: 'Database Migration',
    description: 'Migrate legacy database to new cloud infrastructure',
    status: 'On Hold',
    deadline: '2026-09-01',
    progress: 20,
    createdAt: '2026-05-20T13:00:00Z',
    updatedAt: '2026-05-25T10:15:00Z',
  },
  {
    id: '5',
    name: 'Security Audit',
    description: 'Comprehensive security review and vulnerability assessment',
    status: 'Active',
    deadline: '2026-06-30',
    progress: 80,
    createdAt: '2026-05-05T11:30:00Z',
    updatedAt: '2026-06-05T09:00:00Z',
  },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    projectId: '1',
    title: 'Design Homepage Mockup',
    description: 'Create high-fidelity mockups for the new homepage design',
    status: 'Completed',
    priority: 'High',
    assignedTo: ['3'],
    dueDate: '2026-06-10',
    comments: [
      { id: 'c1', userId: '3', userName: 'Mike Chen', content: 'Initial mockup ready for review', createdAt: '2026-06-08T10:00:00Z' },
      { id: 'c2', userId: '2', userName: 'Sarah Johnson', content: 'Looks great! Minor adjustments needed on the CTA button', createdAt: '2026-06-09T14:30:00Z' },
    ],
    attachments: [
      { id: 'a1', name: 'homepage-mockup-v1.fig', size: 2048000, type: 'application/figma', uploadedAt: '2026-06-08T10:00:00Z' },
    ],
    createdAt: '2026-06-01T09:00:00Z',
    updatedAt: '2026-06-10T16:00:00Z',
  },
  {
    id: '2',
    projectId: '1',
    title: 'Develop Navigation Component',
    description: 'Build responsive navigation with mobile menu support',
    status: 'In Progress',
    priority: 'High',
    assignedTo: ['4'],
    dueDate: '2026-06-12',
    comments: [],
    attachments: [],
    createdAt: '2026-06-02T10:00:00Z',
    updatedAt: '2026-06-05T11:30:00Z',
  },
  {
    id: '3',
    projectId: '1',
    title: 'Optimize Images',
    description: 'Compress and optimize all website images for faster loading',
    status: 'To Do',
    priority: 'Medium',
    assignedTo: ['5'],
    dueDate: '2026-06-15',
    comments: [],
    attachments: [],
    createdAt: '2026-06-03T14:00:00Z',
    updatedAt: '2026-06-03T14:00:00Z',
  },
  {
    id: '4',
    projectId: '1',
    title: 'SEO Optimization',
    description: 'Implement meta tags, structured data, and improve SEO score',
    status: 'To Do',
    priority: 'Low',
    assignedTo: ['3'],
    dueDate: '2026-06-18',
    comments: [],
    attachments: [],
    createdAt: '2026-06-04T09:00:00Z',
    updatedAt: '2026-06-04T09:00:00Z',
  },
  {
    id: '5',
    projectId: '2',
    title: 'Setup React Native Project',
    description: 'Initialize React Native project with necessary dependencies',
    status: 'Completed',
    priority: 'High',
    assignedTo: ['4'],
    dueDate: '2026-05-25',
    comments: [],
    attachments: [],
    createdAt: '2026-05-15T08:00:00Z',
    updatedAt: '2026-05-25T17:00:00Z',
  },
  {
    id: '6',
    projectId: '2',
    title: 'Build Authentication Flow',
    description: 'Implement login, signup, and password reset functionality',
    status: 'In Progress',
    priority: 'High',
    assignedTo: ['4', '5'],
    dueDate: '2026-06-08',
    comments: [
      { id: 'c3', userId: '4', userName: 'Emily Davis', content: 'Working on OAuth integration', createdAt: '2026-06-05T15:00:00Z' },
    ],
    attachments: [],
    createdAt: '2026-05-26T10:00:00Z',
    updatedAt: '2026-06-05T15:30:00Z',
  },
  {
    id: '7',
    projectId: '2',
    title: 'Design App Icons',
    description: 'Create app icons for both iOS and Android platforms',
    status: 'In Review',
    priority: 'Medium',
    assignedTo: ['3'],
    dueDate: '2026-06-07',
    comments: [],
    attachments: [],
    createdAt: '2026-05-28T11:00:00Z',
    updatedAt: '2026-06-06T10:00:00Z',
  },
  {
    id: '8',
    projectId: '5',
    title: 'Penetration Testing',
    description: 'Conduct thorough penetration testing on all endpoints',
    status: 'In Progress',
    priority: 'High',
    assignedTo: ['5'],
    dueDate: '2026-06-09',
    comments: [],
    attachments: [],
    createdAt: '2026-06-01T13:00:00Z',
    updatedAt: '2026-06-05T16:00:00Z',
  },
  {
    id: '9',
    projectId: '5',
    title: 'Update Dependencies',
    description: 'Update all npm packages to latest secure versions',
    status: 'To Do',
    priority: 'High',
    assignedTo: ['4'],
    dueDate: '2026-06-03',
    comments: [],
    attachments: [],
    createdAt: '2026-06-02T09:00:00Z',
    updatedAt: '2026-06-02T09:00:00Z',
  },
  {
    id: '10',
    projectId: '3',
    title: 'Setup API Documentation',
    description: 'Create comprehensive API documentation using Swagger',
    status: 'Completed',
    priority: 'Medium',
    assignedTo: ['3'],
    dueDate: '2026-05-28',
    comments: [],
    attachments: [],
    createdAt: '2026-05-20T10:00:00Z',
    updatedAt: '2026-05-28T14:00:00Z',
  },
];

export const mockActivities: Activity[] = [
  {
    id: '1',
    type: 'task_assigned',
    description: 'Task "Penetration Testing" assigned to James Wilson',
    timestamp: '2026-06-06T10:15:00Z',
    userId: '2',
  },
  {
    id: '2',
    type: 'task_completed',
    description: 'Task "Design Homepage Mockup" marked as completed',
    timestamp: '2026-06-06T09:30:00Z',
    userId: '3',
  },
  {
    id: '3',
    type: 'task_created',
    description: 'New task "SEO Optimization" created in Website Redesign',
    timestamp: '2026-06-04T09:00:00Z',
    userId: '2',
  },
  {
    id: '4',
    type: 'project_created',
    description: 'New project "Security Audit" created',
    timestamp: '2026-05-05T11:30:00Z',
    userId: '1',
  },
  {
    id: '5',
    type: 'task_assigned',
    description: 'Task "Build Authentication Flow" assigned to Emily Davis and James Wilson',
    timestamp: '2026-05-26T10:00:00Z',
    userId: '2',
  },
];

export const mockTeamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@example.com',
    role: 'Admin',
    avatar: '',
    tasksAssigned: 0,
    tasksCompleted: 0,
    workloadPercentage: 0,
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah@example.com',
    role: 'Project Manager',
    avatar: '',
    tasksAssigned: 0,
    tasksCompleted: 0,
    workloadPercentage: 0,
  },
  {
    id: '3',
    name: 'Mike Chen',
    email: 'mike@example.com',
    role: 'Team Member',
    avatar: '',
    tasksAssigned: 4,
    tasksCompleted: 2,
    workloadPercentage: 50,
  },
  {
    id: '4',
    name: 'Emily Davis',
    email: 'emily@example.com',
    role: 'Team Member',
    avatar: '',
    tasksAssigned: 4,
    tasksCompleted: 1,
    workloadPercentage: 75,
  },
  {
    id: '5',
    name: 'James Wilson',
    email: 'james@example.com',
    role: 'Team Member',
    avatar: '',
    tasksAssigned: 3,
    tasksCompleted: 0,
    workloadPercentage: 100,
  },
];
